/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bottle.gltf 
Author: Numbian (https://sketchfab.com/numbian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plastic-water-bottle-f94e72b7c06446cc85816492af416f8f
Title: Plastic water bottle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bottle.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.107, 0.107]} rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Plastic_transparent} position={[0.018, 0.001, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.plastic_blue} position={[0.021, 0.2, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.014, 0.001, 0.014]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.plastic_blue} position={[0.021, 0.197, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.014, 0.001, 0.014]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.label} position={[0.018, 0.001, 0]} scale={[1.011, 0.999, 1.011]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.water} position={[0.018, 0.003, 0]} scale={[0.929, 0.969, 0.929]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bottle.gltf')
